import { Box } from 'components/Box';
import { ContentBlock } from 'components/ContentBlock/ContentBlock';
import Layout from 'components/templates/layout';
import Head from 'next/head';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentBlock>
        <Box component={'p'} padding={{ desktop: 'xxxlarge', tablet: 'large' }}>
          test
        </Box>
      </ContentBlock>
    </Layout>
  );
}
